myproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('sanfu.urls', namespace='sanfu'))
]

sanfu/urls.py
from django.conf.urls import url

from sanfu import views

urlpatterns = [
    url(r'^$', views.index, name='index'),  # 主页
    url(r'^login/$', views.login, name='login'),  # 登录
    url(r'^cart/$', views.cart, name='cart'),  # 购物车
    url(r'^goodsList/$', views.goodsList, name='goodList'),  #
    url(r'goodsMsg/(\d+[_]\d+)/$', views.goodMsg, name='goodsMsg'),  # 商品详情
    url(r'^regiest/$', views.regiest, name='regiest'),  # 注册
    url(r'^outlogin/$', views.outlogin, name='outlogin'),  # 退出登录
    url(r'^uploadhead/$', views.uploadhead, name='uploadhead'),  # 头像上传
    url(r'^checkaccount/$', views.checkaccount, name='checkaccount'),  # 账号验证
    url(r'^addcart/$', views.addcart, name='addcart'),  # 加购物车
    url(r'^changecartcount/$', views.changecartcount, name='changecartcount'),  # 改变购物车商品数量 及单行删除
    url(r'^allselect/$', views.allselest, name='allselect'),  # 全选
    url(r'^singleselect/$', views.singleselect, name='singleselect'),  # 单选
    url(r'^deleteselect/$', views.deleteselect, name='deleteselect'),  # 删除选中
    url(r'^aggregate/$', views.aggregate, name='aggregate'),  # 总计
    url(r'^allcartnumber/$', views.allcartnumber, name='allcartnumber'),  # 获取购物车总数量
    url(r'^generateorder/$', views.generateorder, name='generateorder'),  # 生成订单
    url(r'^order/(\d+)/$', views.order, name='order'), # 订单显示(确认订单)
    url(r'^pay/$', views.pay, name='pay'),  # 支付
    url(r'^alipaynotify/$', views.alipaynotify, name='alipaynotify'),  # 支付成功后的通知页面
    url(r'^alipayreturn/$', views.alipayreturn, name='alipayreturn') # 支付成功后客户端返回页面
]

sanfu/models.py
from django.db import models


# Create your models here.
class User(models.Model):
    username = models.CharField(max_length=80, unique=True)
    userpassword = models.CharField(max_length=256)
    userhead = models.CharField(max_length=256, default='defaultHead.jpg')
    # 令牌
    token = models.CharField(max_length=256, default='')


class Banner(models.Model):
    url = models.CharField(max_length=256)


class Goods(models.Model):
    goodsid = models.CharField(max_length=100)
    img = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    originalPrice = models.CharField(max_length=100)
    presentPrice = models.CharField(max_length=100)

    class Meta:
        abstract = True


class GoodList(Goods):
    class Meta:
        db_table = 'goodslist'


class Hotsingle(Goods):
    class Meta:
        db_table = 'hotsingle'


class Newhot(Goods):
    class Meta:
        db_table = 'newhot'


class Mens(Goods):
    class Meta:
        db_table = 'mens'


class Womens(Goods):
    class Meta:
        db_table = 'womens'


class Goodsdetail(models.Model):
    goodsid = models.CharField(max_length=30)
    name = models.CharField(max_length=200)
    manImg = models.CharField(max_length=50)
    detailImg1 = models.CharField(max_length=50)
    detailImg2 = models.CharField(max_length=50)
    detailImg3 = models.CharField(max_length=50)
    detailImg4 = models.CharField(max_length=50)
    detailImg5 = models.CharField(max_length=50)
    detailImg6 = models.CharField(max_length=50)
    detailImg7 = models.CharField(max_length=50)

    colorImg1 = models.CharField(max_length=50)
    colorImg2 = models.CharField(max_length=50)
    colorImg3 = models.CharField(max_length=50)
    colorImg4 = models.CharField(max_length=50)

    class Meta:
        db_table = 'goodsdatail'


# 购物车
class Cart(models.Model):
    # 用户
    user = models.ForeignKey(User)
    # 商品
    goods = models.ForeignKey(Goodsdetail)
    # 商品数量(选择)
    number = models.IntegerField()
    # 颜色
    color = models.CharField(max_length=20)
    # 大小
    size = models.CharField(max_length=10)
    # 是否选中
    isselect = models.BooleanField(default=True)
    price = models.IntegerField()

    class Meta:
        db_table = 'sanfu_cart'


class Order(models.Model):
    # 用户
    user = models.ForeignKey(User)
    # 订单号
    identifier = models.CharField(max_length=256)
    # 状态
    '''
    -1 过期
    1 未付款
    2 付款未发货
    3 已发货
    4 已签收 未评价
    5 已评价
    6 退款
    '''
    status = models.IntegerField(default=1)
    createtime = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'sanfu_order'


class OrderGoods(models.Model):
    # 订单
    order = models.ForeignKey(Order)
    # 商品
    goods = models.ForeignKey(Goodsdetail)
    price = models.CharField(max_length=20)
    # 数量
    number = models.IntegerField()
    # 大小
    size = models.CharField(max_length=10)
    # 颜色
    color = models.CharField(max_length=30)

    class Meta:
        db_table = 'sanfu_ordergoods'

templates/cart.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta accesskey="百货商城 服装 时尚 鞋帽" />
		<meta content="百货商城 服装 时尚 鞋帽" />
		<title>我的购物车</title>
        {% load static %}
		<link rel='icon' href="{% static 'img/index/icon.ico' %}" type=‘image/x-ico’ />
		<link rel="stylesheet" href="{% static 'css/head.css' %}" />
		<link rel="stylesheet" href="{% static 'css/footer.css' %}" />
		<link rel="stylesheet" href="{% static 'css/iconfont.css' %}" />
		<link rel="stylesheet" href="{% static 'css/gradient.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/cart.css' %}"/>
		<link rel="stylesheet" href="{% static 'css/jquery.idcode.css' %}" />
		<script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/jquery.idcode.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/cart.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/head.js' %}"></script>
	</head>

	<body>
		<!--
        	主head
        -->
		<div class="loginbar">
			<div class="loginbarMain">
				<div>
					<ul>
						<li>
                            {{ username }}
                        </li>
                        {% if userhead %}
                        <li id="userhead">
                            <a href="{% url 'sanfu:uploadhead' %}">
                                <img src="{% static userhead %}" alt="">
                            </a>
                        </li>
                        {% endif %}
						<li>
                            <a href="{% url 'sanfu:outlogin' %}">退出登录</a>
						</li>
						<li>
							<a href="{% url 'sanfu:regiest' %}">免费注册</a>
						</li>
						<li>
							<a href="#" style="background: url({% static 'img/index/nzzz3.jpg' %}) no-repeat;background-position: left;padding-left: 15px;">收藏三福</a>
						</li>
						<li>网店热线: 400-893-9833</li>
						<li style="border: none;height: auto;position: relative;top: -5px;">
							<a href="#" style="background:url({% static 'img/index/wxjgz.png' %}) no-repeat;width: 65px;height:22px;display: block;"></a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="header" style="height: auto;overflow: hidden;">
			<div class="hearderMain" style="margin-top:20px;">
				<ul>
					
					<li>
						<img src="{% static 'img/cart/20160917162638_4.jpg' %}" style="width: 972px;height: 99px;position: absolute;top: 40px;"/>
						<a href="{% url 'sanfu:index' %}"><img src="{% static 'img/index/std_logo.jpg.png' %}" style="margin-right: 60px;position: relative;z-index: 1;" /></a>
					</li>
				</ul>
			</div>
		</div>
		<!--
        	main开始
        -->
        <div class="cartmain">
        	<div class="maintitle">
        		<h4><span class="icon iconfont">&#xe8b3;</span>我的购物车</h4>
        	</div>
        	<div class="mainbody">
        		<table id="mycart">
        			<tr>
        				<th><input type="checkbox" id="checkall" checked="checked"/>全选</th>
        				<th>图片</th>
        				<th>商品信息</th>
        				<th>促销价</th>
        				<th>数量</th>
        				<th>小计</th>
        				<th>操作</th>
        			</tr>
                    {% for cartfoo in cart %}
                    <tr class="goodsinfo" goodsid="{{ cartfoo.goods.goodsid }}">
                        <td><input type='checkbox' checked="checked" class="single"/></td>
                        <td><img src="{% static cartfoo.goods.manImg %}"/></td>
                        <td><span>{{ cartfoo.goods.name }}</span><p> <span class="color">{{ cartfoo.color }}</span>,尺码 <span class="size">{{ cartfoo.size }}</span></p></td>
                        <td><span class="price">{{ cartfoo.price }}</span><span>元</span></td>
                        <td><button class='sub'>-</button><input type='text' class="count" value=' {{ cartfoo.number }}'/><span></span><button class='add'>+</button></td>
                        <td><span>￥</span><span class='total'></span>元</td>
                        <td><a class='delethis'>删除商品</a></td>
                    </tr>

                    {% endfor %}

        		</table>
        		<div class="cartDele">
        			<button id="deleteGoods"><i class="icon iconfont">&#xea19;</i>删除选中的商品</button><span>商品数量总计：<b>0</b></span>
        		</div>
        		<div class="cartToal">
        			<span>商品总价(不含运费)：￥<b>0.00</b>元</span>
        		</div>
        		<div class="cartBtn">
        			<input type="button" value="继续购物" style="background: #ababab;"id="turnBackList"/><input type="button" value="去结算" class="generateorder" style="background: #d90349;" />
        		</div>
        	</div>
        </div>
        <!--
        	main结束
        -->
		<!--
			主footer开始
        -->
				<div style="width: 100%;height: auto;overflow: hidden;" class="gradient">
					
					<div class="ftService">
						<ul>
							<li><img src="{% static 'img/index/zpbz.png' %}" />
								<div>
									<h2>正品保障</h2><span>三福官方品牌</span></div>
							</li>
							<li><img src="{% static 'img/index/mzgx.png' %}" />
								<div>
									<h2>50款</h2><span>每周更新</span></div>
							</li>
							<li><img src="{% static 'img/index/wlyth.png' %}" />
								<div>
									<h2>15天</h2><span>无理由退货</span></div>
							</li>
							<li><img src="{% static 'img/index/hyfw.png' %}" />
								<div>
									<h2>会员服务</h2><span>门店热线：<b>400-1601-606</b></span><span>网店热线：<b>400-8939-833</b></span></div>
							</li>
							<li style="border: none;"><i>银联特约商户</i></li>
						</ul>
					</div>
					<div class="ftNav">
						<ul class="ftNavTitle">
							<li><label style="background: url({% static 'img/index/xszn.png' %}) no-repeat left;padding-left: 30px;">新手指南</label></li>
							<li><label style="background: url({% static 'img/index/fkfs.png' %}) no-repeat left;padding-left: 35px;">付款方式</label></li>
							<li><label style="background: url({% static 'img/index/psfs.png' %}) no-repeat left;padding-left: 30px;">配送方式</label></li>
							<li><label style="background: url({% static 'img/index/shfw.png' %}) no-repeat left;padding-left: 30px;">售后服务</label></li>
							<li><label style="background: url({% static 'img/index/bzzx.png' %}) no-repeat left;padding-left: 30px;">帮助中心</label></li>
							<li><label style="background: url({% static 'img/index/gywm.png' %}) no-repeat left;padding-left: 30px;">关于我们</label></li>
						</ul>
						<ul class="ftNavMsg">
							<li>
								<a href="#">新用户注册</a>
							</li>
							<li>
								<a href="#">找回密码</a>
							</li>
							<li>
								<a href="#">用户协议</a>
							</li>
							<li>
								<a href="#">会员规则</a>
							</li>
							<li>
								<a href="#">积分说明</a>
							</li>
						</ul>
						<ul class="ftNavMsg">
							<li>
								<a href="#">购物流程</a>
							</li>
							<li>
								<a href="#">订单状态</a>
							</li>
							<li>
								<a href="#">优惠劵使用</a>
							</li>
						</ul>
						<ul class="ftNavMsg">
							<li>
								<a href="#">购衣常识</a>
							</li>
							<li>
								<a href="#">发票制度</a>
							</li>
						</ul>
						<ul class="ftNavMsg">
							<li>
								<a href="#">配送方式</a>
							</li>
							<li>
								<a href="#">支付方式</a>
							</li>
						</ul>
						<ul class="ftNavMsg">
							<li>
								<a href="#">退换货政策</a>
							</li>
							<li>
								<a href="#">退货办理流程</a>
							</li>
							<li>
								<a href="#">线上退货流程</a>
							</li>
							<li>
								<a href="#">线下退货流程</a>
							</li>
							<li>
								<a href="#">退款说明</a>
							</li>
						</ul>
						<ul class="ftNavMsg">
							<li>
								<a href="#">三福招聘</a>
							</li>
							<li>
								<a href="#">关于三福</a>
							</li>
							<li>
								<a href="#">官方微博</a>
							</li>
							<li>
								<a href="#">快递查询</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="copyright">
					<p>粤ICP备15015680号 © 2011 SanFu All Rights Reserved.广东三福服装有限公司,禁止非法复制,
						<a href="http://www.miit.gov.cn/">工信部备案查询</a>
						<a href="http://webscan.360.cn/index/checkwebsite/url/sanfu.com"><img src="{% static 'img/index/360safe.png' %}" style="position: relative;top: 10px;" /></a>
					</p>
				</div>
				<!--
			主footer结束
        -->
	</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>

	<head>
		<meta charset="UTF-8">
		<title>用户登录</title>
		<meta accesskey="百货商城 服装 时尚 鞋帽" />
		<meta content="百货商城 服装 时尚 鞋帽" />
        {% load static %}
		<link rel='icon' href="{% static 'img/index/icon.ico' %}" type=‘image/x-ico’ />
		<link rel="stylesheet" href="{% static 'css/head.css' %}" />
		<link rel="stylesheet" href="{% static 'css/login.css' %}" />
		<script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/login.js' %}" ></script>
	</head>

	<body>
		<!--
        	主head
        -->
		<div class="loginbar">
			<div class="loginbarMain">
				<div>
					<ul>
						<li>{% if username %}
                               {{ username }}
                            {% else %}
                                您还未登录
                            {% endif %}
                        </li>
						<li>{% if username %}
                            	<a href="{% url 'sanfu:outlogin' %}">退出登录</a>
                            {% else %}
                                <a href="{% url 'sanfu:login' %}">登录</a>
						    {% endif %}
						</li>
						<li>
							<a href="{% url 'sanfu:regiest' %}">免费注册</a>
						</li>
						<li>
							<a href="#" style="background: url({% static 'img/index/nzzz3.jpg' %}) no-repeat;background-position: left;padding-left: 15px;">收藏三福</a>
						</li>
						<li>网店热线: 400-893-9833</li>
						<li style="border: none;height: auto;position: relative;top: -5px;">
							<a href="#" style="background:url({% static 'img/index/wxjgz.png' %}) no-repeat;width: 65px;height:22px;display: block;"></a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="header" style="height: auto;overflow: hidden;">
			<div class="hearderMain" style="margin-top:20px;">
				<ul>
					<li>
						<a href="{% url 'sanfu:index' %}"><img src="{% static 'img/index/std_logo.jpg.png' %}" style="margin-right: 60px;" /></a>
					</li>
                </ul>
			</div>
			<div class="loginMain">
				<div class="loginAd">
					<img src="{% static 'img/login/20160913155214_4.jpg' %}" />
				</div>
				<div class="loginWay">
					<div>
						<ul class="logintab">
							<li class="loginliact">微信扫码登录
							</li>
							<li>帐号登录</li>
						</ul>
					</div>
					<div class="qrLogin">
						<img src="{% static 'img/login/20160913155214_1.png' %}" />
					</div>
					<div class="formLogin">
						<ul>
							<form action="{% url 'sanfu:login' %}" method="post">
                                <li><input type="text" placeholder="请输入卡号/手机号" id="userName" name="loginName"/></li>
                                <li><input type="password" placeholder="请输入密码" id="passWord" name="loginPwd"/></li>
                                <li><input type="checkbox" value="1" id="remenberMsg"/><label>记住用户名</label><span id="loginerror"></span></li>
                                <p>{{ msg }}</p>
                                <li><input type="submit" value="登录" id="loginBtn"/></li>
                                <li><div><a href="#">忘记密码？</a> | <a href="{% url 'sanfu:regiest' %}">注册帐号</a></div></li>
                            </form>
						</ul>
					</div>
					<div class="loginFriend">
						<span>合作网站帐号登录：</span>
						<a href="#"></a>
					</div>
				</div>

			</div>
		</div>
		<!--
        	footer
        -->
		<div class="loginFooter">
			<ul>
				<li><a href="#">关于三福</a></li>
				<li><a href="#">帮助中心</a></li>
				<li><a href="#">联系我们</a></li>
				<li><a href="#">天猫商城</a></li>
				<li><a href="#">官方微博</a></li>
			</ul>
			<p>粤ICP备1501568(1/3)号 © 2011 SanFu All Rights Reserved.广东省三福百货有限公司,禁止非法复制,<a href="#">工信部备案查询</a></p>
		</div>
	</body>

</html>

templates/order.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta accesskey="百货商城 服装 时尚 鞋帽" />
		<meta content="百货商城 服装 时尚 鞋帽" />
		<title>我的订单</title>
        {% load static %}
		<link rel='icon' href="{% static 'img/index/icon.ico' %}" type=‘image/x-ico’ />
		<link rel="stylesheet" href="{% static 'css/head.css' %}" />
		<link rel="stylesheet" href="{% static 'css/footer.css' %}" />
		<link rel="stylesheet" href="{% static 'css/iconfont.css' %}" />
		<link rel="stylesheet" href="{% static 'css/gradient.css' %}" />
		<link rel="stylesheet" type="text/css" href="{% static 'css/cart.css' %}"/>
		<link rel="stylesheet" href="{% static 'css/jquery.idcode.css' %}" />
        <link rel="stylesheet" href="{% static 'css/order.css' %}">
		<script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/jquery.idcode.js' %}" ></script>
		<script type="text/javascript" src="{% static 'js/head.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/order.js' %}"></script>
	</head>

	<body>
		<!--
        	主head
        -->
		<div class="loginbar">
			<div class="loginbarMain">
				<div>
					<ul>
						<li>
                            {{ username }}
                        </li>
                        {% if userhead %}
                        <li id="userhead">
                            <a href="{% url 'sanfu:uploadhead' %}">
                                <img src="{% static userhead %}" alt="">
                            </a>
                        </li>
                        {% endif %}
						<li>
                            <a href="{% url 'sanfu:outlogin' %}">退出登录</a>
						</li>
						<li>
							<a href="{% url 'sanfu:regiest' %}">免费注册</a>
						</li>
						<li>
							<a href="#" style="background: url({% static 'img/index/nzzz3.jpg' %}) no-repeat;background-position: left;padding-left: 15px;">收藏三福</a>
						</li>
						<li>网店热线: 400-893-9833</li>
						<li style="border: none;height: auto;position: relative;top: -5px;">
							<a href="#" style="background:url({% static 'img/index/wxjgz.png' %}) no-repeat;width: 65px;height:22px;display: block;"></a>
						</li>
					</ul>
				</div>
			</div>
		</div>
		<div class="header" style="height: auto;overflow: hidden;">
			<div class="hearderMain" style="margin-top:20px;">
				<ul>

					<li>
						<img src="{% static 'img/cart/20160917162638_5.jpg' %}" style="width: 972px;height: 99px;position: absolute;top: 40px;"/>
						<a href="{% url 'sanfu:index' %}"><img src="{% static 'img/index/std_logo.jpg.png' %}" style="margin-right: 60px;position: relative;z-index: 1;" /></a>
					</li>
				</ul>
			</div>
		</div>
		<!--
        	main开始
        -->
        <div class="cartmain">
        	<div class="maintitle">
        		<h4><span class="icon iconfont">&#xe8b3;</span>订单详情 <i></i><span id="identifier">订单号:</span><span id="identifiernumber">{{ order.identifier }}</span></h4>
        	</div>
        	<div class="mainbody">
        		<table id="mycart">
        			<tr>
        				<th>图片</th>
        				<th>商品信息</th>
        				<th>促销价</th>
        				<th>数量</th>
        				<th>小计</th>
        			</tr>
                    {% for goods in order.ordergoods_set.all %}
                    <tr class="goodsinfo" >
                        <td><img src="{% static goods.goods.manImg %}"/></td>
                        <td><span>{{ goods.goods.name }}</span><p> <span class="color">{{ goods.color }}</span>,尺码 <span class="size">{{ goods.size }}</span></p></td>
                        <td><span class="price">{{ goods.price }}</span><span>元</span></td>
                        <td><span class="number">{{ goods.number }}</span></td>
                        <td><span>￥</span><span class='total'></span>元</td>
                    </tr>
                    {% endfor %}

        		</table>
        		<div class="cartToal">
        			<span>商品总价(不含运费)：￥<b>0.00</b>元</span>
        		</div>
        		<div class="cartBtn">
        			<input type="button" value="付款" id="pay" style="background: #d90349;" />
        		</div>
        	</div>
        </div>
        <!--
        	main结束
        -->
		<!--
			主footer开始
        -->
				<div style="width: 100%;height: auto;overflow: hidden;" class="gradient">

					<div class="ftService">
						<ul>
							<li><img src="{% static 'img/index/zpbz.png' %}" />
								<div>
									<h2>正品保障</h2><span>三福官方品牌</span></div>
							</li>
							<li><img src="{% static 'img/index/mzgx.png' %}" />
								<div>
									<h2>50款</h2><span>每周更新</span></div>
							</li>
							<li><img src="{% static 'img/index/wlyth.png' %}" />
								<div>
									<h2>15天</h2><span>无理由退货</span></div>
							</li>
							<li><img src="{% static 'img/index/hyfw.png' %}" />
								<div>
									<h2>会员服务</h2><span>门店热线：<b>400-1601-606</b></span><span>网店热线：<b>400-8939-833</b></span></div>
							</li>
							<li style="border: none;"><i>银联特约商户</i></li>
						</ul>
					</div>
					<div class="ftNav">
						<ul class="ftNavTitle">
							<li><label style="background: url({% static 'img/index/xszn.png' %}) no-repeat left;padding-left: 30px;">新手指南</label></li>
							<li><label style="background: url({% static 'img/index/fkfs.png' %}) no-repeat left;padding-left: 35px;">付款方式</label></li>
							<li><label style="background: url({% static 'img/index/psfs.png' %}) no-repeat left;padding-left: 30px;">配送方式</label></li>
							<li><label style="background: url({% static 'img/index/shfw.png' %}) no-repeat left;padding-left: 30px;">售后服务</label></li>
							<li><label style="background: url({% static 'img/index/bzzx.png' %}) no-repeat left;padding-left: 30px;">帮助中心</label></li>
							<li><label style="background: url({% static 'img/index/gywm.png' %}) no-repeat left;padding-left: 30px;">关于我们</label></li>
						</ul>
						<ul class="ftNavMsg">
							<li>
								<a href="#">新用户注册</a>
							</li>
							<li>
								<a href="#">找回密码</a>
							</li>
							<li>
								<a href="#">用户协议</a>
							</li>
							<li>
								<a href="#">会员规则</a>
							</li>
							<li>
								<a href="#">积分说明</a>
							</li>
						</ul>
						<ul class="ftNavMsg">
							<li>
								<a href="#">购物流程</a>
							</li>
							<li>
								<a href="#">订单状态</a>
							</li>
							<li>
								<a href="#">优惠劵使用</a>
							</li>
						</ul>
						<ul class="ftNavMsg">
							<li>
								<a href="#">购衣常识</a>
							</li>
							<li>
								<a href="#">发票制度</a>
							</li>
						</ul>
						<ul class="ftNavMsg">
							<li>
								<a href="#">配送方式</a>
							</li>
							<li>
								<a href="#">支付方式</a>
							</li>
						</ul>
						<ul class="ftNavMsg">
							<li>
								<a href="#">退换货政策</a>
							</li>
							<li>
								<a href="#">退货办理流程</a>
							</li>
							<li>
								<a href="#">线上退货流程</a>
							</li>
							<li>
								<a href="#">线下退货流程</a>
							</li>
							<li>
								<a href="#">退款说明</a>
							</li>
						</ul>
						<ul class="ftNavMsg">
							<li>
								<a href="#">三福招聘</a>
							</li>
							<li>
								<a href="#">关于三福</a>
							</li>
							<li>
								<a href="#">官方微博</a>
							</li>
							<li>
								<a href="#">快递查询</a>
							</li>
						</ul>
					</div>
				</div>
				<div class="copyright">
					<p>粤ICP备15015680号 © 2011 SanFu All Rights Reserved.广东三福服装有限公司,禁止非法复制,
						<a href="http://www.miit.gov.cn/">工信部备案查询</a>
						<a href="http://webscan.360.cn/index/checkwebsite/url/sanfu.com"><img src="{% static 'img/index/360safe.png' %}" style="position: relative;top: 10px;" /></a>
					</p>
				</div>
				<!--
			主footer结束
        -->
	</body>
</html>

templates/uploadhead.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>头像上传</title>
</head>
<body>

<form action="/uploadhead/" method="post" enctype="multipart/form-data" onsubmit="return false">
    <input type="file" name="userhead">
    <input type="submit" value="上传">
</form>
<p></p>
<script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}"></script>
<script type="text/javascript" src="{% static 'js/uploadhead.js' %}"></script>

</body>
</html>